---
name: CI

on:
  pull_request:
    branches:
      - main
      - "v*"

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  validate-lint-and-unit-test:
    name: Run validation, linters and unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.4"]
        experimental: [false]
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          extensions: "grpc"

      - name: Validate
        run: make validate-composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Lint
        run: make lint

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@bb5570805858670fd33787e9ded60b8c1140b2a1 # main

      - name: Run unit tests
        run: make test
